const iataCodesToCity = {
  // Europe
  "CDG": "Paris Charles de Gaulle",
  "ORY": "Paris Orly",
  "MAD": "Madrid",
  "BCN": "Barcelona",
  "LHR": "London Heathrow",
  "LGW": "London Gatwick",
  "STN": "London Stansted",
  "LTN": "London Luton",
  // Thailand
  "BKK": "Bangkok",
  "CNX": "Chiang Mai",
  "HKT": "Phuket",
  // South East Asia
  "SIN": "Singapore",
  "KUL": "Kuala Lumpur",
  "DPS": "Bali",
  "CGK": "Jakarta",
  "HAN": "Hanoi",
  "SGN": "Ho Chi Minh City",
  "PNH": "Phnom Penh",
  "REP": "Siem Reap",
  "RGN": "Yangon",
  "KOS": "Sihanoukville",
  // Middle East
  "DXB": "Dubai",
  "DOH": "Doha",
  "AUH": "Abu Dhabi",
  "JED": "Jeddah",
  "RUH": "Riyadh",
  "KWI": "Kuwait City",
  // US
  "JFK": "New York JFK",
  "EWR": "New York Newark",
  "LAX": "Los Angeles",
  "SFO": "San Francisco",
  "SEA": "Seattle",
  "ORD": "Chicago",
  "BOS": "Boston",
  "MIA": "Miami",
  "IAD": "Washington DC",
  "ATL": "Atlanta",
  "DFW": "Dallas",
  "DEN": "Denver",
  "LAS": "Las Vegas",
  "PHX": "Phoenix",
  "CLT": "Charlotte",
  "MCO": "Orlando",
  "MSP": "Minneapolis",
  "DTW": "Detroit",
  "PHL": "Philadelphia",
  "SLC": "Salt Lake City",
  "BWI": "Baltimore",
  "FLL": "Fort Lauderdale",
  "SAN": "San Diego",
  "TPA": "Tampa",
  "IAD": "Washington Dulles",
  "HNL": "Honolulu",
  "AUS": "Austin",
  "MSY": "New Orleans",
  "PDX": "Portland",
  "SMF": "Sacramento",
  "SAT": "San Antonio",
  "SJC": "San Jose",
  "SNA": "Santa Ana",
  "RSW": "Fort Myers",
  "HOU": "Houston",
  "OAK": "Oakland",
  "PIT": "Pittsburgh",
  "RDU": "Raleigh",
  "STL": "St Louis",
  "BNA": "Nashville",
  "DAL": "Dallas Love Field",
  "MCI": "Kansas City",
  "CLE": "Cleveland",
  "IND": "Indianapolis",
  "MKE": "Milwaukee",
  "CMH": "Columbus",
  "SDF": "Louisville",
  "BUF": "Buffalo",
  "OMA": "Omaha",
  "PBI": "West Palm Beach",
  "MSY": "New Orleans",
  "PVD": "Providence",
  "BDL": "Hartford",
  "BHM": "Birmingham",
  "ABQ": "Albuquerque",
  "OKC": "Oklahoma City",
  "TUL": "Tulsa",
  "MEM": "Memphis",
  "RIC": "Richmond",
  "ORF": "Norfolk",
  "NUQ": "Mountain View",
}

// export in commonJS as function
module.exports = iataCodesToCity;