org: hugolarrousse
app: app-hugo
service: flight-price-alert

frameworkVersion: '3'
useDotenv: true


provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-3
  timeout: 30

functions:
  cron:
    handler: handler-cron.cron
    events:
      - schedule:
          rate: cron(0 6-20 * * ? *)

package:
  patterns:
    - '!test.js'